# Generated by Django 6.0.2 on 2026-02-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
